# Generated by Django 6.0.1 on 2026-01-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Tên Combo/Món"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="Giá bán"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="foods/", verbose_name="Hình ảnh"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang kinh doanh"),
                ),
            ],
            options={
                "verbose_name": "Bắp nước",
                "verbose_name_plural": "Quản lý Bắp nước",
            },
        ),
    ]
