# Generated by Django 6.0.1 on 2026-01-19 13:09

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
        ("cinema", "0002_alter_cinema_options_alter_movie_options_and_more"),
        ("warehouse", "0002_alter_inventorylog_options_alter_product_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Đơn đặt vé",
                "verbose_name_plural": "Danh sách Đơn vé",
            },
        ),
        migrations.AlterModelOptions(
            name="concessionitem",
            options={
                "verbose_name": "Combo đã đặt",
                "verbose_name_plural": "Chi tiết Bắp nước",
            },
        ),
        migrations.AlterModelOptions(
            name="promotion",
            options={
                "verbose_name": "Khuyến mãi",
                "verbose_name_plural": "Quản lý Khuyến mãi",
            },
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={
                "verbose_name": "Vé xem phim",
                "verbose_name_plural": "Chi tiết Vé",
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=0,
                default=Decimal("0"),
                max_digits=12,
                verbose_name="Số tiền giảm",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="final_amount",
            field=models.DecimalField(
                decimal_places=0,
                default=Decimal("0"),
                max_digits=12,
                verbose_name="Thực thu",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="hold_expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Hết hạn giữ vé"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CASH", "Tiền mặt"),
                    ("MOMO", "Ví MoMo"),
                    ("ZALOPAY", "ZaloPay"),
                    ("BANK", "Chuyển khoản/Thẻ"),
                    ("VNPAY", "VNPay"),
                ],
                max_length=20,
                null=True,
                verbose_name="Phương thức TT",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="transaction_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Mã giao dịch Ngân hàng",
            ),
        ),
        migrations.AddField(
            model_name="concessionitem",
            name="total_price",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=12, verbose_name="Thành tiền"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="promotion",
            name="description",
            field=models.TextField(blank=True, verbose_name="Mô tả"),
        ),
        migrations.AddField(
            model_name="promotion",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Kích hoạt"),
        ),
        migrations.AddField(
            model_name="promotion",
            name="max_discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=12,
                null=True,
                verbose_name="Giảm tối đa (cho %)",
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="name",
            field=models.CharField(
                default=0, max_length=255, verbose_name="Tên chương trình"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="promotion",
            name="start_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Ngày bắt đầu"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="check_in_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Thời gian vào"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="is_checked_in",
            field=models.BooleanField(default=False, verbose_name="Đã soát vé"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="code",
            field=models.CharField(
                editable=False, max_length=10, unique=True, verbose_name="Mã vé"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="promotion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bookings.promotion",
                verbose_name="Mã KM áp dụng",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="showtime",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="cinema.showtime",
                verbose_name="Suất chiếu",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Nhân viên bán",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("HOLD", "Đang giữ vé"),
                    ("PENDING", "Chờ xử lý"),
                    ("PAID", "Đã thanh toán"),
                    ("CANCELLED", "Đã hủy"),
                ],
                default="HOLD",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=0,
                default=Decimal("0"),
                max_digits=12,
                verbose_name="Tổng tiền",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Khách hàng",
            ),
        ),
        migrations.AlterField(
            model_name="concessionitem",
            name="price",
            field=models.DecimalField(
                decimal_places=0, max_digits=12, verbose_name="Đơn giá lúc mua"
            ),
        ),
        migrations.AlterField(
            model_name="concessionitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="warehouse.product",
                verbose_name="Sản phẩm",
            ),
        ),
        migrations.AlterField(
            model_name="concessionitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Số lượng"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="code",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Mã giảm giá"
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="discount_type",
            field=models.CharField(
                choices=[("PERCENT", "%"), ("AMOUNT", "VND")],
                default="PERCENT",
                max_length=10,
                verbose_name="Loại giảm",
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="discount_value",
            field=models.DecimalField(
                decimal_places=0, max_digits=12, verbose_name="Giá trị giảm"
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="min_spend",
            field=models.DecimalField(
                decimal_places=0,
                default=Decimal("0"),
                max_digits=12,
                verbose_name="Chi tiêu tối thiểu",
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="quantity_limit",
            field=models.IntegerField(default=100, verbose_name="Tổng số lượng mã"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="used_count",
            field=models.IntegerField(default=0, verbose_name="Đã sử dụng"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="valid_until",
            field=models.DateTimeField(verbose_name="Hạn sử dụng"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="price",
            field=models.DecimalField(
                decimal_places=0, max_digits=12, verbose_name="Giá vé"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="seat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cinema.seat",
                verbose_name="Ghế",
            ),
        ),
    ]
