# Generated by Django 6.0.1 on 2026-01-08 06:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cinema",
            options={
                "verbose_name": "Rạp chiếu",
                "verbose_name_plural": "Danh sách Rạp",
            },
        ),
        migrations.AlterModelOptions(
            name="movie",
            options={
                "ordering": ["-release_date"],
                "verbose_name": "Phim",
                "verbose_name_plural": "Quản lý Phim",
            },
        ),
        migrations.AlterModelOptions(
            name="review",
            options={
                "verbose_name": "Đánh giá",
                "verbose_name_plural": "Danh sách Đánh giá",
            },
        ),
        migrations.AlterModelOptions(
            name="room",
            options={
                "verbose_name": "Phòng chiếu",
                "verbose_name_plural": "Danh sách Phòng",
            },
        ),
        migrations.AlterModelOptions(
            name="seat",
            options={
                "ordering": ["row", "number"],
                "verbose_name": "Ghế ngồi",
                "verbose_name_plural": "Sơ đồ Ghế",
            },
        ),
        migrations.AlterModelOptions(
            name="showtime",
            options={
                "ordering": ["start_time"],
                "verbose_name": "Suất chiếu",
                "verbose_name_plural": "Quản lý Suất chiếu",
            },
        ),
        migrations.AddField(
            model_name="cinema",
            name="hotline",
            field=models.CharField(blank=True, max_length=20, verbose_name="Hotline"),
        ),
        migrations.AddField(
            model_name="movie",
            name="age_rating",
            field=models.CharField(
                choices=[
                    ("P", "P - Mọi lứa tuổi"),
                    ("T13", "T13 - Trên 13 tuổi"),
                    ("T16", "T16 - Trên 16 tuổi"),
                    ("T18", "T18 - Trên 18 tuổi"),
                    ("K", "K - Khán giả dưới 13 tuổi có người bảo hộ"),
                ],
                default="P",
                max_length=5,
                verbose_name="Nhãn tuổi",
            ),
        ),
        migrations.AddField(
            model_name="seat",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Có thể sử dụng"),
        ),
        migrations.AlterField(
            model_name="cinema",
            name="address",
            field=models.TextField(verbose_name="Địa chỉ"),
        ),
        migrations.AlterField(
            model_name="cinema",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Tên rạp"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="cast",
            field=models.TextField(blank=True, null=True, verbose_name="Diễn viên"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(blank=True, verbose_name="Mô tả"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="director",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Đạo diễn"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="duration_minutes",
            field=models.IntegerField(
                help_text="Nhập số phút", verbose_name="Thời lượng (phút)"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genre",
            field=models.CharField(
                choices=[
                    ("ACTION", "Hành động"),
                    ("ROMANCE", "Tình cảm"),
                    ("HORROR", "Kinh dị"),
                    ("COMEDY", "Hài"),
                    ("SCI_FI", "Viễn tưởng"),
                    ("ANIMATION", "Hoạt hình"),
                    ("DRAMA", "Tâm lý"),
                    ("FAMILY", "Gia đình"),
                ],
                default="ACTION",
                max_length=20,
                verbose_name="Thể loại",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="poster",
            field=models.ImageField(upload_to="movies/posters/", verbose_name="Poster"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="release_date",
            field=models.DateField(verbose_name="Ngày khởi chiếu"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="status",
            field=models.CharField(
                choices=[
                    ("COMING_SOON", "Sắp chiếu"),
                    ("NOW_SHOWING", "Đang chiếu"),
                    ("STOPPED", "Ngừng chiếu"),
                ],
                default="COMING_SOON",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Tên phim"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="trailer_url",
            field=models.URLField(blank=True, verbose_name="Link Trailer"),
        ),
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(verbose_name="Bình luận"),
        ),
        migrations.AlterField(
            model_name="review",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="cinema.movie",
                verbose_name="Phim",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                default=5,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Điểm (1-5)",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người dùng",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="cinema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cinema.cinema",
                verbose_name="Thuộc rạp",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Tên phòng"),
        ),
        migrations.AlterField(
            model_name="room",
            name="type",
            field=models.CharField(
                choices=[("2D", "Standard 2D"), ("3D", "3D"), ("IMAX", "IMAX")],
                default="2D",
                max_length=20,
                verbose_name="Định dạng",
            ),
        ),
        migrations.AlterField(
            model_name="seat",
            name="number",
            field=models.IntegerField(verbose_name="Số ghế"),
        ),
        migrations.AlterField(
            model_name="seat",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seats",
                to="cinema.room",
                verbose_name="Phòng",
            ),
        ),
        migrations.AlterField(
            model_name="seat",
            name="row",
            field=models.CharField(max_length=5, verbose_name="Hàng ghế"),
        ),
        migrations.AlterField(
            model_name="seat",
            name="seat_type",
            field=models.CharField(
                choices=[
                    ("STD", "Ghế thường"),
                    ("VIP", "Ghế VIP"),
                    ("SWT", "Sweetbox (Cặp đôi)"),
                ],
                default="STD",
                max_length=3,
                verbose_name="Loại ghế",
            ),
        ),
        migrations.AlterField(
            model_name="showtime",
            name="base_price",
            field=models.DecimalField(
                decimal_places=0, max_digits=10, verbose_name="Giá vé cơ bản (VNĐ)"
            ),
        ),
        migrations.AlterField(
            model_name="showtime",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cinema.movie",
                verbose_name="Phim",
            ),
        ),
        migrations.AlterField(
            model_name="showtime",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cinema.room",
                verbose_name="Phòng chiếu",
            ),
        ),
        migrations.AlterField(
            model_name="showtime",
            name="start_time",
            field=models.DateTimeField(verbose_name="Giờ bắt đầu"),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("user", "movie")},
        ),
    ]
