# Generated by Django 6.0.1 on 2026-01-19 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventorylog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Phiếu kho",
                "verbose_name_plural": "Lịch sử Nhập/Xuất",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["category", "name"],
                "verbose_name": "Sản phẩm kho",
                "verbose_name_plural": "Danh sách Kho",
            },
        ),
        migrations.RemoveField(
            model_name="inventorylog",
            name="change_amount",
        ),
        migrations.AddField(
            model_name="inventorylog",
            name="quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="Số lượng"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inventorylog",
            name="trans_type",
            field=models.CharField(
                choices=[("IMPORT", "Nhập kho"), ("EXPORT", "Xuất kho / Hủy")],
                default="IMPORT",
                max_length=10,
                verbose_name="Loại phiếu",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("FOOD", "Đồ ăn (Bắp, Snack)"),
                    ("DRINK", "Đồ uống (Nước ngọt)"),
                    ("PACKAGING", "Bao bì (Ly, Túi)"),
                    ("OTHER", "Khác"),
                ],
                default="FOOD",
                max_length=20,
                verbose_name="Danh mục",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="code",
            field=models.CharField(
                default=0, max_length=50, unique=True, verbose_name="Mã hàng (SKU)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="min_threshold",
            field=models.IntegerField(
                default=10, verbose_name="Mức báo động (Tối thiểu)"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[
                    ("PCS", "Cái/Lon/Chai"),
                    ("KG", "Kilogram"),
                    ("BOX", "Thùng"),
                    ("BAG", "Bao"),
                ],
                default="PCS",
                max_length=10,
                verbose_name="Đơn vị tính",
            ),
        ),
        migrations.AlterField(
            model_name="inventorylog",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="warehouse.product",
                verbose_name="Sản phẩm",
            ),
        ),
        migrations.AlterField(
            model_name="inventorylog",
            name="reason",
            field=models.TextField(blank=True, verbose_name="Ghi chú / Lý do"),
        ),
        migrations.AlterField(
            model_name="inventorylog",
            name="staff",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Nhân viên",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Đang kinh doanh"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Tên sản phẩm"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=12, verbose_name="Giá nhập/vốn"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_quantity",
            field=models.IntegerField(default=0, verbose_name="Tồn kho"),
        ),
    ]
