# Generated by Django 6.0.1 on 2026-01-19 13:09

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoyaltyPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "earning_rate",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("10000"),
                        max_digits=10,
                        verbose_name="Số tiền để tích 1 điểm",
                    ),
                ),
                (
                    "redemption_rate",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("1000"),
                        max_digits=10,
                        verbose_name="Giá trị quy đổi 1 điểm (VND)",
                    ),
                ),
                (
                    "min_order_value_to_redeem",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Đơn tối thiểu để dùng điểm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chính sách tích điểm",
                "verbose_name_plural": "Cấu hình Tích điểm",
            },
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Tên chương trình"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Mã giảm giá"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("PERCENT", "%"), ("AMOUNT", "VND")],
                        default="PERCENT",
                        max_length=10,
                        verbose_name="Loại giảm",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="Giá trị giảm"
                    ),
                ),
                (
                    "min_spend",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Chi tiêu tối thiểu",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Số tiền giảm trực tiếp",
                    ),
                ),
                (
                    "max_discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        verbose_name="Giảm tối đa (cho %)",
                    ),
                ),
                (
                    "quantity_limit",
                    models.IntegerField(default=100, verbose_name="Tổng số lượng mã"),
                ),
                (
                    "used_count",
                    models.IntegerField(default=0, verbose_name="Đã sử dụng"),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Ngày bắt đầu"
                    ),
                ),
                ("valid_until", models.DateTimeField(verbose_name="Hạn sử dụng")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Kích hoạt"),
                ),
            ],
            options={
                "verbose_name": "Mã giảm giá",
                "verbose_name_plural": "Quản lý Khuyến mãi",
            },
        ),
    ]
